# Generated by Django 4.1.3 on 2022-11-17 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
