# Generated by Django 4.1.3 on 2022-11-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_tag_alter_blogcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tg_art',
            field=models.ManyToManyField(to='blog.article'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
