# Generated by Django 4.1.3 on 2023-02-18 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_protuct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Protuct',
            new_name='Product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
