# Generated by Django 4.1.3 on 2023-02-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_meta_descriprion_product_meta_keywords_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='meta_descriprion',
            new_name='meta_description',
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_tittle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Tittle'),
        ),
    ]
